version: '3.8'

services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql-questionary
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=bn_laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=bitnami_laravel
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql  
    networks:
      - laravel_network

  app:
    image: 'bitnami/laravel:latest'
    container_name: laravel-questionary
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mysql 
      - DB_PORT=3306
      - DB_DATABASE=bitnami_laravel
      - DB_USERNAME=bn_laravel
      - DB_PASSWORD=secret
      - BITNAMI_APP_USER=1000 
      - BITNAMI_APP_GROUP=1000 
    volumes:
      - ./questionary-Proyect:/app
    networks:
      - laravel_network
    depends_on:
      - mysql 

volumes:
  mysql_data:
    driver: local
  laravel_data:
    driver: local

networks:
  laravel_network:
    driver: bridge
